Views
taldr27/blog pull request #5
Opened 2023-02-01 20:20 UTC by taldr27

### In this milestone I:
- Added view files for users and posts.
- Added `erb` code inside the view files to grab data from the database.
- Added counters to each post and user.
- Added basic styling to the views.
- Populated DB with some data.
<img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="5%"/>

2023-02-01 23:43 UTC, Munsa1 requested changes
Hi @taldr27, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 23:43 UTC, Munsa1 commented on app/views/users/index.html.erb
> +  <% end %>
- [ ] Kindly follow the given wireframe, so as to position your content as in the given wireframe

Your design
![image](https://user-images.githubusercontent.com/81932478/216192178-c43dcc84-e428-44b2-90ac-172a2b59d464.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/216192234-3c3ff58b-ba42-4a65-a923-81491e908541.png)

2023-02-01 23:43 UTC, Munsa1 commented on app/views/users/show.html.erb
> +</div>
- [ ] Kindly align the `see all posts` to the center as in the given template

Your design
![image](https://user-images.githubusercontent.com/81932478/216192929-7f7d1a3d-e261-49e1-b167-319d891d4edb.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/216192839-7f58e67a-6897-45fc-83d2-e3d6cfaa7450.png)

2023-02-01 23:47 UTC, taldr27 commented
@Munsa1 thank you very much for your help and review, I'll fix those requested changes asap.

2023-02-02 00:45 UTC, codecaiine approved these changes
Hi @taldr27 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Great views setup :heavy_check_mark: 
- Great requirement application :heavy_check_mark: 
- No rubocop errors :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 20:35 UTC, merged